const constants = {
  CHANGE_QUERY: 'CHANGE_QUERY',
  PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  PRODUCT_GET_ERROR: 'PRODUCT_GET_ERROR',
  PRODUCT_SEARCH_SUCCESS: 'PRODUCT_SEARCH_SUCCESS',
  PRODUCT_SEARCH_ERROR: 'PRODUCT_SEARCH_ERROR',
  BREADCRUMB_SUCCESS: 'BREADCRUMB_SUCCESS',
  BREADCRUMB_ERROR: 'BREADCRUMB_ERROR',
};

export default constants;